
version: '3'
services:
  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_DIRECTORY=/bitnami/spark/data
    ports:
      - "7077:7077"
      - '8081:8080' 
    networks:
      - spark-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

  spark-worker-1:
    image: bitnami/spark:3.3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=8g
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_INSTANCES=3
    ports:
      - "8082:8082"
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:3.3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=8g
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_WORKER_WEBUI_PORT=8084
      - SPARK_WORKER_INSTANCES=3
    ports:
      - "8084:8084"
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-3:
    image: bitnami/spark:3.3.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=8g
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_WORKER_WEBUI_PORT=8085
      - SPARK_WORKER_INSTANCES=3
    ports:
      - "8085:8085"
    depends_on:
      - spark-master
    networks:
      - spark-network

  
  
networks:
  spark-network:
    external: true
